# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.
#
# Declared variables for the helm chart

clusterConfig:
  port: 9090
  batchSize: 32
  jobs:
    ps:
      isGPU: false
      num: 2
      image: cpuImage
    worker:
      isGPU: true
      num: 2
      image: gpuImage

traindir: /azure/share/training-distrib

cpuImage:
  repository: <REPO NAME>
  name: distrib-tensorflow-cars
  tag: ps
  
gpuImage: 
  repository: <REPO NAME>
  name: distrib-tensorflow-cars
  tag: worker-gpu

storage:
  accountbase64: accountname
  keybase64: accountkey
  sharename: sharename
