# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.

FROM tensorflow/tensorflow:latest

ENV ROOTDIR=/src/

RUN mkdir -p "${ROOTDIR}/python/"

WORKDIR "${ROOTDIR}"

COPY src/python/*.py "${ROOTDIR}/python/"
