# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.

FROM tensorflow/tensorflow:latest-gpu

ENV ROOTDIR=/src/
RUN mkdir -p "${ROOTDIR}"

WORKDIR "${ROOTDIR}"

COPY src/. "${ROOTDIR}"